MAINCC := $(wildcard *.cc)
TARGET := test_$(basename $(notdir ${MAINCC}))
TEST_FLAGS := -g

ifneq ("$(wildcard case.mk)","")
include case.mk
endif

ifndef DIM
DIM := 2
endif

COMPFLAGS :=
COMPFLAGS += -DCMF_DIM=${DIM}

main: setup
	${CC_HOST} ${TEST_FLAGS} ${COMPFLAGS} ${CURRENT_ICONFIG} ${MAINCC} -o ${TARGET} ${CURRENT_LCONFIG}

setup:
	mkdir -p output
	ln -sf ${CURRENT_BASEIDIR}/util/makefile.latex output/makefile

clean:
	-rm ${TARGET}

test: clean main
	${VALG} ./${TARGET}
	${MAKE} -C output -f makefile
