IFFOUND :=
ifneq ("$(wildcard main.tex)","")
IFFOUND := look
endif

.PHONY: final
final: ${IFFOUND}

.PHONY: look
look:
	pdflatex -halt-on-error main.tex
	pdflatex -halt-on-error main.tex
	rm -f *.log *.aux *.nav *.out *.toc *.snm
