MAINCC := $(wildcard *.cc)
TARGET := test_$(basename $(notdir ${MAINCC}))
TEST_FLAGS := -g

ifneq ("$(wildcard testParams.mk)","")
include testParams.mk
endif

ifndef PARALLEL_TEST_RUN
PARALLEL_TEST_RUN := 0
endif

ifndef PARALLEL_PROCESSES
PARALLEL_PROCESSES := 1
endif

ifndef DOLATEXOUTPUT
DOLATEXOUTPUT := 0
endif

ifeq (${DOLATEXOUTPUT}, 1)
DOLATEXOUTPUTTARGET := latex
else
DOLATEXOUTPUTTARGET :=
endif

ifndef DIM
DIM := 2
endif

ifeq (${PARALLEL_TEST_RUN}, 1)
MPIRUN := $(shell which mpirun) -np ${PARALLEL_PROCESSES}
VALG :=
else
MPIRUN := 
endif

COMPFLAGS :=
COMPFLAGS += -DCMF_DIM=${DIM}

main: setup
	${CC_HOST} ${TEST_FLAGS} ${COMPFLAGS} ${CURRENT_ICONFIG} ${MAINCC} -o ${TARGET} ${CURRENT_LCONFIG}

setup:
	mkdir -p output
	ln -sf ${CURRENT_BASEIDIR}/util/makefile.latex output/makefile

clean:
	-rm ${TARGET}

.PHONY: test
test: clean main ${DOLATEXOUTPUTTARGET}
	${VALG} ${MPIRUN} ./${TARGET}

latex:
	${MAKE} -C output -f makefile
