#ifndef CONFIG_PARAMS_H
#define CONFIG_PARAMS_H
//The included file should be generated by the build system and include definitions for the following:
//CMF_DIM
//CMF_ENABLE_STACK_BLOB
//CMF_PARALLEL
//CMF_ZLIB_EXT_ENABLE
//CUDA_ENABLE
#include "cmfbuild.h"
#endif